"""add bodega cat column

Revision ID: 1a25c5bd4cf3
Revises: ca9c0e46b610
Create Date: 2024-12-03 12:19:40.590228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a25c5bd4cf3'
down_revision = 'ca9c0e46b610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delis_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bodega_cat', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delis_table', schema=None) as batch_op:
        batch_op.drop_column('bodega_cat')

    # ### end Alembic commands ###
