"""add delis and burgers

Revision ID: 413ab362b40b
Revises: 
Create Date: 2024-12-04 09:58:01.060612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413ab362b40b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delis_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('has_bodega_cat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hamburgers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deli_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deli_id'], ['delis_table.id'], name=op.f('fk_hamburgers_table_deli_id_delis_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hamburgers_table')
    op.drop_table('delis_table')
    # ### end Alembic commands ###
