"""add deli model

Revision ID: 445d8ad5bb65
Revises: 
Create Date: 2024-12-03 10:31:21.537215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445d8ad5bb65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delis_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('has_ice_cream', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delis_table')
    # ### end Alembic commands ###
