"""remove price, add star_rating

Revision ID: 84e81ea4624d
Revises: 97d7ae093436
Create Date: 2024-07-31 10:43:44.383205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e81ea4624d'
down_revision = '97d7ae093436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delis_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_rating', sa.Integer(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delis_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=True))
        batch_op.drop_column('star_rating')

    # ### end Alembic commands ###
