"""empty message

Revision ID: 8ab1818364f5
Revises: e4febec837e5
Create Date: 2025-01-28 11:21:25.162523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab1818364f5'
down_revision = 'e4febec837e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magazines_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('magazine_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors_table.id'], name=op.f('fk_articles_table_author_id_authors_table')),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazines_table.id'], name=op.f('fk_articles_table_magazine_id_magazines_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles_table')
    op.drop_table('magazines_table')
    op.drop_table('authors_table')
    # ### end Alembic commands ###
